name: AppName
description: App Description
author: Auto mail <@mail> 
homepage: http://

dependencies: 
  sass: any
  grinder:
      git: 'git@github.com:google/grinder.dart.git'

transformers:
- sass:
    style: compact                
    compass: true
    copy-sources: false
