name: AppName
description: App Description
author: Auto mail <@mail> 
homepage: http://
dependencies: 
  sass: any
transformers:
- sass:
    style: compact                
    compass: true
    copy-sources: false
